[package]
name = "aoc-2022-18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convolve2d = "0.1.0"
nom = "7.1.1"
